spring.datasource.url=jdbc:mysql://localhost:3306/otel
spring.datasource.username=root
spring.datasource.password=nursena
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.application.name=backend
spring.security.user.name=admin
spring.security.user.password=123456
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=*
spring.security.enabled=false
#jwt.secret=antalyaotel_secret_key_dont_share
#jwt.expiration=86400000 # 1 g�n (milisaniye cinsinden)
#server.port=9090

# Spring Security log seviyesini DEBUG yap
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
jwt.secret=utsP783XXVBNxbdgdtvQ+RdrAlzJQHIQNTij1Yfi9NJ5FHz0NhcFG/cnMnyS431FeBMx2MLSLawo0iE145OQmw==
jwt.expiration=3600000
logging.level.org.springframework.security.web=DEBUG
logging.level.com.antalyaotel.config.JwtAuthenticationFilter=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=otelsmtp@gmail.com
spring.mail.password=vkktktxwbvxeiypq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
spring.http.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
//spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:57373/Callback
google.client.id=352435397896-gd7okv0mb113s7ab3ovbl8iieibq3ngl.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:57373/Callback
spring:
autoconfigure:
exclude: org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration









